### ISSUE TITLE
Data not being pulled in for blocks 

### ISSUE THREAD

**Issue by ccasazza22** [getblocklab/block-lab#522] opened 2020-03-11 16:08 UTC
## Bug summary

I am trying to create a CTA button, following the instructions on the website exactly. But it doesn’t seem to be pulling in the values for the url and button text field

## Steps to reproduce

1. Create a block with fields, title, text, button-text and button-url 
2. Create the PHP 
3. Run in Wordpress

## Expected behavior

Should show a title, the text and then a button with a clickable url 

## Actual behavior

Only the title is being pulled in. 

## Additional information

I’ve tried running it in several
Blocks. I’ve tested the html and css to make sure they work. But it seems the data for everything but the title is not being pulled in. 

## Versions

 - WordPress version: 5
 - Block Lab version: latest https://github.com/getblocklab/block-lab/releases -->
 - Gutenberg plugin version (if active):
 - OS:
 - Browser:
 - Device:

**Comment by kienstra** [comment] 2020-03-11 16:34
Hi @valuegamers,
Thanks for bringing this up, and for your details.

1. Are there any other block-related plugins active?

2. Could you please share the Edit Block screen of the block, like:

![eidt-block-s](https://user-images.githubusercontent.com/4063887/76440539-9b901c80-6383-11ea-8c4e-a30b2eae2748.png)

3. Could you please paste the PHP from the block template? For example:

```php
<?php
/**
 * Template for test-image block.
 */

$field_name = 'test-text';
?>
<p><?php esc_html_e( 'Here is the className with block_value():', 'bl-testing-templates' ); ?></p>
<?php echo block_value( 'className' ); ?>

<p><?php esc_html_e( 'And here is the className with block_field():', 'bl-testing-templates' ); ?></p>
<?php block_field( 'className' ); ?>
<div class="<?php echo esc_attr( block_value( 'className' ) ); ?>">
	<p><?php block_field( $field_name ); ?></p>
</div>

```

Thanks, and sorry to start out with a lot of questions.

**Comment by ccasazza22** [comment] 2020-03-11 16:40
1. No other related block plugins. But attached screenshot in case
something sticks out

2. Attached screenshot

3. Here is the code snippet

<div>
> <h3><?php block_field('title'); ?></h3>
> <p><?php block_field( ‘description’ ); ?></p>
> <a href="<?php block_field( ‘button-link’ ); ?>"><?php block_field(
> ‘button-text’ ); ?></a>
> </div>
>

**Comment by kienstra** [comment] 2020-03-11 17:03
Hi @valuegamers,
Thanks for your fast reply.

It looks like the attached screenshots might not have made it into this issue. Would you be able to add them again?

Thanks!

**Comment by ccasazza22** [comment] 2020-03-11 18:06
Hey Ryan, 

Here are the screenshots! 
<img width="1440" alt="Screen Shot 2020-03-11 at 12 37 06 PM" src="https://user-images.githubusercontent.com/38638470/76448855-68f51c80-63a1-11ea-8aa4-4fed03b1bdc5.png">
![Uploading Screen Shot 2020-03-11 at 12.38.36 PM.png…]()

**Comment by kienstra** [comment] 2020-03-11 23:52
Thanks for the screenshots, and your great details. I'll work on reproducing this.

**Comment by ccasazza22** [comment] 2020-03-12 20:26
Hey @kienstra wanted to see if there was any headway with this issue? 

Thanks! 

Craig

**Comment by kienstra** [comment] 2020-03-13 02:17
Sorry for the delay. I'm looking at this now.

**Comment by kienstra** [comment] 2020-03-13 02:29
Hi @valuegamers,
Could you please try this as the template:

```php
<div>
 <h3><?php block_field('title'); ?></h3>
 <p><?php block_field( 'description' ); ?></p>
 <a href="<?php block_field( 'button-link' ); ?>"><?php block_field( 'button-text' ); ?></a>
 </div>
```

It looks like the original template has backticks ` or some other character instead of single quotes '. Though maybe that's from emailing it.

```php
<div>
 <h3><?php block_field('title'); ?></h3>
 <p><?php block_field( ‘description’ ); ?></p> <!-- backticks here -->
 <a href="<?php block_field( ‘button-link’ ); ?>"><?php block_field(
 ‘button-text’ ); ?></a> <!-- backticks here -->
 </div>
```

**Comment by kienstra** [comment] 2020-03-17 00:58
Closing this, as the suggestion above fixed it in my local. But feel free to comment if it didn't.

**Closed as completed by kienstra** 2020-03-17 00:58 UTC

**Comment by ccasazza22** [comment] 2020-03-17 01:02
Sorry! Yes! This worked and i think i felt like too much of an idiot to
respond back. Thank you again!!

**Comment by kienstra** [comment] 2020-03-17 01:45
No problem at all, glad it worked 😄 

I really appreciate you using Block Lab.
