### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#8] opened 2018-08-01 06:59 UTC
Implement unit testing.

**Comment by kienstra** [comment] 2019-08-28 03:51
#404 is related to this, and will capture much of the integration and unit tests for now.

**Comment by kienstra** [comment] 2019-09-20 20:15
#404 is a duplicate of this. I should have simply added on to this issue. 

But if it's alright, I'll close this issue in favor of #404.

**Closed as completed by kienstra** 2019-09-20 20:15 UTC
