### ISSUE TITLE
Error loading block: Cookie nonce is invalid

### ISSUE THREAD

**Issue by MattKevan** [getblocklab/block-lab#270] opened 2019-03-28 12:47 UTC
I've just pushed my site from local to staging, and now most of the Block Lab blocks I created are displaying blank with the error ```Error loading block: Cookie nonce is invalid```. Blocks display fine on the front end, it's just the editor preview that's broken.

Looking in the browser web inspector I get a 403 forbidden error for each block that's not displaying. 

`http://co-create.flywheelsites.com/wp-json/wp/v2/block-renderer/block-lab/cc-hero-banner?context=edit&attributes% ... post_id=5&_locale=user
Failed to load resource: the server responded with a status of 403 (Forbidden)`

There seems to be an issue with Gutenberg if the site URL and Wordpress URLs are different, but in my case they're the same.

https://github.com/WordPress/gutenberg/issues/1761

Any thoughts on this would be appreciated.

**Comment by lukecarbis** [comment] 2019-03-28 13:23
@MattKevan I encountered this same error once while demoing Block Lab live to an audience, and I couldn't figure out what was going wrong. It ended up fixing itself, which made me wonder if there could be a cache or transient issue at work here.

Thanks for the instructions on how to reproduce the problem, I'll try to replicate it when I next get a chance.

**Comment by MattKevan** [comment] 2019-03-28 15:06
Looking into it a bit deeper, only blocks with images have the problem. Delete the image and the error goes away, return the image and so does the error. 

I found this applied to both newly-created blocks and ones that had been pushed to stage with the migration. I also have caching switched off, so I'd have expected the problem to have gone away by now if it was a cache issue.

**Comment by lukecarbis** [comment] 2019-04-14 00:28
@MattKevan If #285 doesn't work, could you try disabling WP Super Cache (or any other caching plugin that you've got installed), and resaving your permalinks?

If that still doesn't help, try following some of the steps outlined here:
https://wordpress.org/support/topic/jetpack-4-3-error-cookie-nonce-is-invalid/

**Comment by lukecarbis** [comment] 2019-04-14 00:29
For what it's worth, I received this error when I was connected to a wireless network that was trying to redirect traffic to its network login screen. I have a strong feeling this is happening because WordPress is not receiving the URLs it expects.

**Comment by kienstra** [comment] 2019-04-15 04:26
Hi @MattKevan, 
Thanks for letting us know about this.

Have you seen problems like this with other parts of the block editor, not just Block Lab?

**Comment by lukecarbis** [comment] 2019-04-23 02:25
I've spent a lot of time investigating this, and I'm not sure there's a problem we're able to fix in Block Lab. Closing for now unless someone can show steps to replicate that don't also effect non-block-lab dynamic blocks.

**Closed as completed by lukecarbis** 2019-04-23 02:25 UTC
Labels: bug
